### ISSUE TITLE
Network logs

### ISSUE THREAD

**Issue by dsafonso** [ripe-tech/ripe-rainbow#126]
## Description

Some white automatic tests don't pass and the image we have is a white page any layout, and on the log I expect have some network logs to identify the problem.

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Have network issues on the log. |
| **Observed** | Don't have any network log |

## Environment

| Key | Value |
| --- | --- |
| **Device** | server |
| **Operating System** | Linux |
| **Browser** | Chrome 89.0.4389.82 |
| **CHROME_DRIVER** | 89.0.4389.23 |
| **Instance (URL)** | [Jenkins](https://jenkins.platforme.com/) |

## Screens
[summary.SummaryTest.add_different_personalization_for_each_shoe.ripe-rainbow-browser.log](https://github.com/ripe-tech/ripe-rainbow/files/7944422/summary.SummaryTest.add_different_personalization_for_each_shoe.ripe-rainbow-browser.log)

capture of the failed test:
![image](https://user-images.githubusercontent.com/24550956/151227936-90498da6-a0e3-4d04-9c35-17b8a4e15515.png)

Log:
![image](https://user-images.githubusercontent.com/24550956/151228000-12987146-a789-4346-a3db-e2f60b36c0bd.png)

**Comment by joao-conde** [comment]
@dsafonso trying to reproduce it locally I get no network logs:

![Screenshot from 2022-01-31 04-45-34](https://user-images.githubusercontent.com/16060539/151740360-3216c3d9-2cba-4a4d-aabe-71c0fc3ec253.png)

But I do get the error on the left. I don't have access to Jenkins, can you check if there are such logs?

Also, can you confirm me the version we use in Jenkins for the Chrome browser and driver?

**Comment by joao-conde** [comment]
After some investigation it seems that we are clearing local and session storages with `clear_local_storage` and `clear_session_storage` when local or session storage exists, for example, for the `"data:"` protocol.

Currently propose this fix: https://github.com/ripe-tech/ripe-rainbow/tree/jc/126-clear-storage-skip-data-protocol

But since it touches caching the potential to break some tests is high and therefore I will run all tests before.

**Comment by joao-conde** [comment]
The original issue seems in fact that we do not have any network logs for this test

**Comment by joao-conde** [comment]
To sum this up:

- upgrade chrome/chromedriver to a newer release (for example chrome 97 works perfectly); this has the nice "side effect" of using a newer chrome version instead of an outdated one
- https://github.com/ripe-tech/ripe-rainbow/pull/127 clearing local and session storages is done only if the protocol allows for it (`"data:"` protocol does not for example)

**Comment by dsafonso** [comment]
Test OK :+1:  the failed test is not related to this card
